### ISSUE TITLE
Draw error when changing layout

### ISSUE THREAD

**Issue by ychyss** [ivmartel/dwv#1466]
still using `tests/pacs/viewer.js`

1. In single layergroup, I draw some thing in it
2. change the layout to mpr
3. try scroll any window, got error (change tool to scroll before I scroll in layergroup doesn't work.)

![image](https://github.com/ivmartel/dwv/assets/15881179/94c89280-adc4-4edb-8a08-e2e4282d83f5)

**Comment by ivmartel** [comment]
This should be fixed in the latest code. Which version are you using?

**Comment by ychyss** [comment]
I‘m using 0.32.0. Maybe it is because of no deletion of handle of positionchange event on #app in Draw.js. When I change layout,  LayerGroup just empty the array of layers `this.#layers = [];`, without destruction.

**Comment by ychyss** [comment]
I traced this bug and find that:

I change the name of single layergroup to `layerGroupSingle`  to distinguish with the MPR's `layerGroupA`, and add some code in `#activateCurrentPositionShapes of Draw.js`

```js
  #activateCurrentPositionShapes(visible, layerGroup) {
    const drawLayer = layerGroup.getActiveDrawLayer();
    if (!drawLayer) {
      console.log('layerGroup no ActiveDrawLayer: ', layerGroup);
      return;
    }
    const drawController = drawLayer.getDrawController();
    // layerGroup.getActiveDrawLayer().getDrawController();
...
```
then I got:
![image](https://github.com/ivmartel/dwv/assets/15881179/35c6f35c-a829-4d2a-966a-2b1b96aa700f)

that means the previous event handle still exists.

**Comment by ivmartel** [comment]
This is the same as #1423, no? It should be fixed in 49d58de. Check out if you get the error in the trunk demo viewer.

There are two available demo viewers, the stable and the trunk one. The stable one will, today, use v0.32.0. The trunk one uses the latest code. The links are:
- stable: https://ivmartel.github.io/dwv/demo/stable/viewer.html
- trunk: https://ivmartel.github.io/dwv/demo/trunk/viewer.html

**Comment by ychyss** [comment]
![image](https://github.com/ivmartel/dwv/assets/15881179/c2ea6a6a-80f4-4557-98c7-787f20d94e8e)

thanks! I see the info in console.. :-) 

 I'm sorry to bother you, but I forgot to mention this issue earlier.

And may I ask when version 0.33.0 will be released?

**Comment by ivmartel** [comment]
This is a warning for when you call `getActiveDrawLayer` and there is no active draw layer index, possibly because the layer was deleted (for example via a `app.removeDataViewConfig`).

About the release, I'm still fiddling with the add/remove/update data view config, not clear when this will be finished. I'll say not before 1 or 2 months...

**Comment by ychyss** [comment]
oh...it sounds like a big work...good luck~

**Comment by ivmartel** [comment]
Closing for now, feel free to comment if you need.
