### ISSUE TITLE
Not a valid DICOM file (no magic DICM word found) on JPEG image for v0.27.1

### ISSUE THREAD

**Issue by yuliujpl** [ivmartel/dwv#815]
Hi!

I've been having trouble using the app.loadURL function in dwv.js against jpg/png files. If I use dicom images in the URL, there's no issues, but when I try jpg/png URLs, I get the error in the title.

I see previously you fixed this issue in 2015 with a previous version of dwv (https://github.com/ivmartel/dwv/issues/125). However, it seems the current version has erased the resolution that may have solved that.

Is there any guidance how I can programmatically load jpeg/gif/png or even CT files using the loadURL function?

Thank you so much.

**Comment by ivmartel** [comment]
I think this was solved in #721.

**Comment by yuliujpl** [comment]
Hi,

Thanks, I looked at the code and couldn't deduce how the fix will correspond to how I call the loadURL function correctly. Here is the loadURL statement I'm making:
myapp.loadURLs(["test.jpg"], [{name:"contentType", value:"image/jpeg"}]);

This is still throwing the following error:
applauncher.js:178 Error: Not a valid DICOM file (no magic DICM word found and first element not in 0x0008 group)

Am I calling the loadURLs incorrectly?

Thanks again,
David

**Comment by ivmartel** [comment]
The previous code could end up returning that the dicom data loader could load jpeg images since the if was badly formed. And when the dicom loader loads jpeg data, it does not have the dicom preamble and therefore sends the error you see.

**Comment by ivmartel** [comment]
I hope this answers your question, closing for now, feel free to comment if you need.
